checker/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import Check
import re
import login.views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'checker';
urlpatterns = [
	url(r'^$',views.indexpage,name='indexpage'),
	url(r'^deepcheck/',Check.as_view(),name = 'deepcheck'),
	url(r'^viewdocument/(?P<string>[^/]+)$',views.viewdocument,name = 'viewdocument'),
	url(r'^institutionlogin/$', login.views.institution_login_and_register,name='institutionlogin'),
	url(r'^login/$', login.views.user_login_and_register,name='login'),
	
	url(r'^logout/$', login.views.logout_page),
	url(r'^contact	/', login.views.logout_page	),
	url(r'^register/', login.views.register),
    url(r'^plagchecker',views.geturls,name='geturls'),
    url(r'^subusers/$',views.subusers,name='subusers'),
    url(r'^addusers/$',views.addusers,name='addusers'),
	url(r'^upload/$', views.model_form_upload, name='model_form_upload'),
	url(r'^show/(.*)/$',views.show,name='show'),
	# url(r'^show/(?P<string>[^/]+)$',views.viewdocument,name='viewdocument'),
	# url(r'^download/(.*)/$',views.report,name='report'),
	url(r'^deleteuser/(?P<username>[\w|\W.-]+)/$', views.deleteuser,name= 'deleteuser'),
	url(r'^changecredit/(?P<username>[\w|\W.-]+)/$', views.changecredit,name= 'changecredit'), 
	url(r'^change/(?P<username>[\w|\W.-]+)/$', views.change,name= 'change'), 
	url(r'^dashboard/',views.dashboard,name='dashboard'),
	url(r'^imageUpload/', views.FileView.as_view()),
	]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plagiarismchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rest_framework import routers
from checker.views import ApiViewSet
from django.conf import settings
from django.views.static import serve
router = routers.DefaultRouter()
router.register(r'/api',ApiViewSet)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('checker.urls')),
    url(r'^doc',include(router.urls))
]

if settings.DEBUG:
    urlpatterns+=[
        url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,})
    ]

checker/models.py
import uuid
import os
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
randomid = uuid.uuid4()

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (randomid, ext)
    return os.path.join('documents/', filename)

class Profile(models.Model):
    # created_by=models.ForeignKey(User, related_name='created_by_user')
    created_by=models.ForeignKey(User, on_delete='created_by_user')


class Subuser(models.Model):
    user = models.ForeignKey(User,null=True,on_delete=models.DO_NOTHING,related_name = 'user')
    created_by = models.ForeignKey(User,null=True,on_delete=models.DO_NOTHING,related_name='created_by_user')

class Data(models.Model):
    data = models.TextField()
    user = models.ForeignKey(User,null=True,on_delete=models.DO_NOTHING,)
    def __str__(self):
        return self.data

	# keywords = models.CharField(max_length=500)
#
class Apidocument(models.Model):
    iden = models.CharField(max_length=255)
    document = models.FileField(upload_to='media/documents')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Institution(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    flag = models.IntegerField(blank = True,default = 1)
    name = models.CharField(max_length = 30,blank = True,default='')
    mobile_no = models.IntegerField(blank=  True,default = 0)
    designation = models.CharField(max_length = 30,blank = True, default = '')
    contact_person = models.CharField(max_length = 30,blank  = True,default = '')
    institution_name = models.CharField(max_length=255, blank=True, default='')
    address = models.CharField(max_length=255, blank=True, default='')
    pincode = models.CharField(max_length=255, blank=True, default='')
    def __str__(self):
        return self.user
    

class Credits(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    credits = models.DecimalField(max_digits=8, decimal_places=0,default="1000")



@receiver(post_save, sender=User)
def create_user_credits(sender, instance, created, **kwargs):
    if created:
        Credits.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_credits(sender, instance, **kwargs):
    instance.credits.save()


@receiver(post_save, sender=User)
def create_user_institution(sender, instance, created, **kwargs):
    if created:
        Institution.objects.create(user=instance)
        

@receiver(post_save, sender=User)
def save_user_institution(sender, instance, **kwargs):
    instance.institution.save()

class Document(models.Model):

    user = models.ForeignKey(User,null=True,on_delete=models.DO_NOTHING,)
    result = models.DecimalField(max_digits=50,decimal_places=5,null=True)
    credits = models.DecimalField(max_digits=8, decimal_places=0,default="1000")
    description = models.CharField(max_length=255, blank=True, default='')
    document = models.CharField(max_length=255, )
    uploaded_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.document

checker/forms.py
from django import forms
from .models import Data,Document
class DataForm(forms.ModelForm):
	# post = forms.CharField(max_length=280)

	class Meta:
		model = Data
		fields = ('data',)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', )

checker/views.py
# from django.core.urlresolvers import reverse  <- for django 1.11
from django.urls import reverse
# for working with pdfs
import PyPDF2

# for rendering html pages
from django.shortcuts import render

# for working with json
import json

# decarators
from django.contrib.auth.decorators import login_required

# random integers
from random import randint

# similarity finding module
import difflib

# working with time
import datetime

# created forms
from .forms import DataForm,DocumentForm

# for working with urls
from urllib.parse import urlencode, urlparse, parse_qs

# regular expressions
import re

# for storing data in system
from django.core.files.storage import FileSystemStorage

# to make html pretty
from lxml.html import fromstring

# accessing webpages
from requests import get
import requests

# extracting html
from bs4 import BeautifulSoup

# io operations
import io
from os.path import splitext
import random

# math functions
import math

# no idea
from collections import Counter

# redirecting webpages
from django.http import HttpResponseRedirect

# models
from .models import Document,Data,randomid,Apidocument,Credits,Subuser,User,Institution

# view classes
from django.views import View
from rest_framework.views import APIView

# django-rest-framework
from rest_framework.parsers import MultiPartParser, FormParser,FileUploadParser
from rest_framework.response import Response
from rest_framework import status
from .serializers import DataSerializer
from rest_framework import viewsets
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa
import docx
from django.http import FileResponse, Http404

# for highlighting pdf
import fitz

from rest_framework.decorators import api_view
MAX_RETRIES = 20
session = requests.Session()
adapter = requests.adapters.HTTPAdapter(max_retries=MAX_RETRIES)
session.mount('https://', adapter)
session.mount('http://', adapter)
#
class ApiViewSet(viewsets.ModelViewSet):
    queryset = Apidocument.objects.all().order_by('-uploaded_at')
    serializer_class = DataSerializer
    # def list(self, request, *args, **kwargs):
    #     return Response({'something': 'my custom JSON'})


class FileView(APIView):
  parser_classes = (MultiPartParser, FormParser)
  def post(self, request, *args, **kwargs):
    file_serializer = DataSerializer(data=request.data)
    if file_serializer.is_valid():
      file_serializer.save()
      return Response(file_serializer.data, status=status.HTTP_201_CREATED)
    else:
      return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def changecredit(request,username):
    subuserlist = Subuser.objects.filter(created_by = request.user)
    return render(request,'changecredits.html',{'subusers':subuserlist,'username':username})

def change(request,username):

    subuserlist = Subuser.objects.filter(created_by = request.user)
    curr_user = request.user
    cr = int(request.POST['creditfield'])
    if(curr_user.credits.credits<=cr):
        msg = "Sorry you do not have enough credits to change credits"
        return render(request,'changecredits.html',{'msg':msg,'cli':curr_user,'subusers':subuserlist})
    user = User.objects.get(username = username)
    if 'add' in request.POST:
        user.credits.credits += cr
        curr_user.credits.credits-=cr
    elif 'sub' in request.POST:
        user.credits.credits-=cr
        curr_user.credits.credits+=cr            
    curr_user.save()
    user.save()
    subuserlist = Subuser.objects.filter(created_by = request.user)
    return render(request,'changecredits.html',{'subusers':subuserlist,})


def deleteuser(request, username):    
    try:
        # u = User.objects.get(pk = username.id)
        u = User.objects.get(username = username)
        u.delete()
        subuserlist = Subuser.objects.filter(created_by = request.user)
        return render(request,'subusers.html',{'subusers':subuserlist})

    except User.DoesNotExist:
        # messages.error(request, "User doesnot exist")    
        return render(request, 'dashboard1.html')

    except Exception as e: 
        return render(request, 'dashboard1.html',{'msg':"invalid user"})

    return render(request, 'dashboard1.html') 

def addusers(request):
    curr_user = request.user
    documents = Document.objects.filter(user=request.user)
    if(curr_user.credits.credits<=1000):
        msg = "Sorry you do not have enough credits to add user"
        return render(request,'dashboard1.html',{'msg':msg,'documents':documents,'cli':curr_user})
    if request.method == 'POST' and 'insregisterbutton' in request.POST:
        print("inside elif")
        try:
            user = User.objects.get(username__iexact=request.POST['username'])
            msg = 'User name already exists try different one'
            return render(request,'addusers.html',{'msg':msg})
        except User.DoesNotExist:
            curr_user.credits.credits -= 1000
            curr_user.save()
            user = User.objects.create_user(username=request.POST['username'],password=request.POST['password1'],email=request.POST['email'])
            user.credits.credits = 1000
            user.institution.flag = 0
            user.save()
            # user = User.objects.get(pk = user.id)
            print("inside institution")
            subuserobj = Subuser(user = user,created_by=request.user)
            subuserobj.save()
            subusers = Subuser.objects.filter(created_by = request.user)
            
            return render(request,'subusers.html',{'subusers':subusers})
    return render(request,'addusers.html',{})

def subusers(request):
    subuserlist = Subuser.objects.filter(created_by = request.user)
    return render(request,'subusers.html',{'subusers':subuserlist})


browsers = [
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6',
            'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.6) Gecko/2009011912 Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)',
            'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.6) Gecko/2009020911 Ubuntu/8.10 (intrepid) Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)',
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.48 Safari/525.19',
            'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET CLR 3.0.04506.648)',
            'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.6) Gecko/2009020911 Ubuntu/8.10 (intrepid) Firefox/3.0.6',
            'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.5) Gecko/2008121621 Ubuntu/8.04 (hardy) Firefox/3.0.5',
            'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/3.2.1 Safari/525.27.1',
            'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)',
            'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)',
            'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
            'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0',
            ]
WORD = re.compile(r'\w+')
headers={
	'User-Agent': browsers[random.randint(0, len(browsers) - 1)],
	'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
	'Accept-Language': 'en-us,en;q=0.5'
	}

	
def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])

     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)

     if not denominator:
        return 0.0
     else:
         d1 = float(numerator) / denominator
         print(d1)
         return d1
def text_to_vector(text):
     words = WORD.findall(text)
     return Counter(words)
def calplag(file1_data,file2_data):

    text1 = file1_data
    text2  = file2_data
    vector1 = text_to_vector(text1)
    vector2 = text_to_vector(text2)
    cosine = get_cosine(vector1, vector2)
    print ('Cosine:', cosine)
    return cosine


def dataextract(urllist,textss,x):
    sentenceslist = []
    datalist = []
    similarity_ratio = []
    inptextsent = []
    randomfiles = []


    m = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', textss)
    for senten in m:
        sentenceslist.append(senten)
    if x!=1:
    	toplist = urllist[:5]
    else:
    	toplist = urllist[:1]
    for l in toplist:
        f = io.open('file1.txt','w', encoding="utf-8")
        f.truncate()
        f.close()
        rad = randint(0, 10000000000000)
        randomfiles.append(rad)

        print(l)
        if (l!='/' and len(l)>2):
            parsed = urlparse(l)
            root, ext = splitext(parsed.path)
            if ext=='.pdf':
                html = get('http://%s'%(l),verify = False,headers = headers,stream=True)
                with open("syed.pdf","wb") as pdf:
                    for chunk in html.iter_content(chunk_size=1024):

                         # writing one chunk at a time to pdf file
                         if chunk:
                             pdf.write(chunk)
                    pdf.close()
                    docdata = open('syed.pdf','rb')
                    pdfReader = PyPDF2.PdfFileReader(docdata)

                    num_pages = pdfReader.numPages
                    count = 0
                    text = ""

                    while count < num_pages:
                        pageObj = pdfReader.getPage(count)
                        count +=1

checker/templates/changecredits.html
{% extends 'dash.html' %}
{% block stylesheet %}
<style>
    .btn.btn-info {
        background-color: $purple;
        border-color: $purple;
        outline: none;
        &:hover {
            background-color: darken($purple, 10%);
            border-color: darken($purple, 10%);
        }
        &:active, &:focus {
            background-color: lighten($purple, 5%);
            border-color: lighten($purple, 5%);
        }
    }
</style>
{% endblock %}
{% block body %}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">SubUsers</li>
    <li style="position: absolute !important;right: 0 !important"> Available Credits :  {{user.credits.credits}}</li>
</ol>
<div class="container card">
    <div class="form-group row">

    </div>
    <div class="">

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        <table class="table table-bordered table-striped table-sm">
            <thead class="alert-warning">
                <tr>
                    <th>Sl.no</th>
                    <th>UserName</th>
                    <th>Email</th>
                    <th>Credits Assigned</th>
                    <th style="text-align: center;">Action</th>
                </tr>
            </thead>
            <tbody>


                {% for user in subusers %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td>{{ user.user.username}}</td>
                    <td>{{ user.user.email }}</td>
                    <td>{{ user.user.credits.credits }}</td>
                    {% if user.user.username != username %}
                    <td><center><a class="btn btn-sm btn-warning" href="{% url 'checker:changecredit' user.user.username %}"><span class="fa fa-edit"></span> Edit credits</a>
                        <!-- <a class="btn btn-sm btn-danger" href="#"><span class="fa fa-trash"></span> Delete User</a> -->
<!-- {% url 'checker:deleteuser' user.user.username %} -->
                        {% else %}
                         <td><center>
                            <form method="post" action="{% url 'checker:change' user.user.username %}">{% csrf_token %}
                                    <input type="text" name="creditfield">
                                    <input type="submit" name="add" value='add' style="background-color: orange;">
                                    <input type="submit" name="sub" value='sub'style="background-color: orange;">

                             </form>
                            
                        <!-- <a class="btn btn-sm btn-danger" href="#"><span class="fa fa-trash"></span> Delete User</a> -->


                        {% endif %}
                    </center></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>
{% if msg %}
<script type="text/javascript">
  alert("{{ msg }}");
</script>
{% endif %}
{% endblock %}
{% block javascript %}
<script>
    $(document).on('click', '.browse', function () {
        var file = $(this).parent().parent().parent().find('.file');
        file.trigger('click');
    });
    $(document).on('change', '.file', function () {
        $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
    });
</script>

{% endblock %}

checker/templates/dashboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <table cellpadding=20>
        {% for document in documents %}
            <tr>
                <td><a href="{{ document.document.url }}">{{ document}}</a> </td>
                <td></td>
                <td></td>
                <td><a href="delete/{{ document.document.name }}"> Delete</a></td>

            </tr>
        {% endfor %}
        </table>


  </body>
</html>

checker/templates/dashboard1.html
{% extends 'dash.html' %}
{% block stylesheet %}
<style>
    .btn.btn-info {
        background-color: $purple;
        border-color: $purple;
        outline: none;
        &:hover {
            background-color: darken($purple, 10%);
            border-color: darken($purple, 10%);
        }
        &:active, &:focus {
            background-color: lighten($purple, 5%);
            border-color: lighten($purple, 5%);
        }
    }
</style>
{% endblock %}
{% block body %}
<!-- Breadcrumbs-->

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">File History</li>
    <li style="position: absolute !important;right: 0 !important"> Available Credits :  {{cli.credits.credits}}</li>
</ol>
<div class="container card">
    <div class="form-group row">

    </div>
    <div class="">

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        <table class="table table-bordered table-striped table-sm">
            <thead class="alert-warning">
                <tr>
                    <th>Sl.no</th>
                    <th>File Name</th>
                    <th>Checked At</th>
                    <th>Result</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>


                {% for document in documents %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td>{{ document.document }}</td>
                    <td>{{ document.uploaded_at }}</td>
                    <td>{{ document.result }}%</td>
                    <td><center><a class="btn btn-sm btn-warning" href="{% url 'checker:viewdocument' string=document.document %}"><span class="fa fa-edit"></span> View</a>
                        <!-- <a class="btn btn-sm btn-danger" href="#"><span class="fa fa-trash"></span> Delete</a> -->
                    </center></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% if msg %}
<script type="text/javascript">
  alert("{{ msg }}");
</script>
{% endif %}
</div>

{% endblock %}
{% block javascript %}
<script>
    $(document).on('click', '.browse', function () {
        var file = $(this).parent().parent().parent().find('.file');
        file.trigger('click');
    });
    $(document).on('change', '.file', function () {
        $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
    });
</script>

{% endblock %}

checker/templates/model_form_upload.html
{% extends "base.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="www.google.com">Return to home</a></p>
{% endblock %}

checker/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'signin' %}">sign in</a> now.
  </p>
{% endblock %}

checker/templates/password_reset_confirm.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
 {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
</body>
</html>

checker/templates/password_reset_done.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
 <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
</body>
</html>

checker/templates/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

checker/templates/report.html
<!DOCTYPE html>
<html>
<head>
<title>Report</title>
<style>
div{
 max-width:100%;
 word-wrap: break-word;
 padding: 1rem;
  font-size: 140%;
 }
 span { 
  background-color: yellow;
  color: black;
}



html, body {
    max-width: 100%;
}
p {
  word-wrap: break-word;
}
body, input {
  margin: 5;
  font: .9em Verdana, 'Lucida Grande', Geneva, Lucida, sans-serif;
  }
</style>
</head>
 <body>
<div>
  {% for i in text %}
  {% if i.0 == '0'%}
	   <span>{{ i }} </span>
    {% else %}
      {{i}}
     {% endif %}
    {% endfor%}
</div>
</body>
</html>

checker/templates/subusers.html
{% extends 'dash.html' %}
{% block stylesheet %}
<style>
    .btn.btn-info {
        background-color: $purple;
        border-color: $purple;
        outline: none;
        &:hover {
            background-color: darken($purple, 10%);
            border-color: darken($purple, 10%);
        }
        &:active, &:focus {
            background-color: lighten($purple, 5%);
            border-color: lighten($purple, 5%);
        }
    }
</style>
{% endblock %}
{% block body %}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">SubUsers</li>
    <li style="position: absolute !important;right: 0 !important"> Available Credits :  {{user.credits.credits}}</li>
</ol>
<div class="container card">
    <div class="form-group row">

    </div>
    <div class="">

        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        <table class="table table-bordered table-striped table-sm">
            <thead class="alert-warning">
                <tr>
                    <th>Sl.no</th>
                    <th>UserName</th>
                    <th>Email</th>
                    <th>Credits Assigned</th>
                    <th style="text-align: center;">Action</th>
                </tr>
            </thead>
            <tbody>


                {% for user in subusers %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td>{{ user.user.username}}</td>
                    <td>{{ user.user.email }}</td>
                    <td>{{ user.user.credits.credits }}</td>
                    <td><center><a class="btn btn-sm btn-warning" href="{% url 'checker:changecredit' user.user.username %}"><span class="fa fa-edit"></span> Edit credits</a>
                        <!-- <a class="btn btn-sm btn-danger" href="#"><span class="fa fa-trash"></span> Delete User</a> -->
<!-- {% url 'checker:deleteuser' user.user.username %} -->
                    </center></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>

{% endblock %}
{% block javascript %}
<script>
    $(document).on('click', '.browse', function () {
        var file = $(this).parent().parent().parent().find('.file');
        file.trigger('click');
    });
    $(document).on('change', '.file', function () {
        $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
    });
</script>

{% endblock %}