checker/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import Check
import re
import login.views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'checker';
urlpatterns = [
	url(r'^$',views.indexpage,name='indexpage'),
	url(r'^deepcheck/',Check.as_view(),name = 'deepcheck'),
	url(r'^viewdocument/(?P<string>[^/]+)$',views.viewdocument,name = 'viewdocument'),
	url(r'^institutionlogin/$', login.views.institution_login_and_register,name='institutionlogin'),
	url(r'^login/$', login.views.user_login_and_register,name='login'),
	
	url(r'^logout/$', login.views.logout_page),
	url(r'^contact	/', login.views.logout_page	),
	url(r'^register/', login.views.register),
    url(r'^plagchecker',views.geturls,name='geturls'),
    url(r'^subusers/$',views.subusers,name='subusers'),
    url(r'^addusers/$',views.addusers,name='addusers'),
	url(r'^upload/$', views.model_form_upload, name='model_form_upload'),
	url(r'^show/(.*)/$',views.show,name='show'),
	# url(r'^show/(?P<string>[^/]+)$',views.viewdocument,name='viewdocument'),
	# url(r'^download/(.*)/$',views.report,name='report'),
	url(r'^deleteuser/(?P<username>[\w|\W.-]+)/$', views.deleteuser,name= 'deleteuser'),
	url(r'^changecredit/(?P<username>[\w|\W.-]+)/$', views.changecredit,name= 'changecredit'), 
	url(r'^change/(?P<username>[\w|\W.-]+)/$', views.change,name= 'change'), 
	url(r'^dashboard/',views.dashboard,name='dashboard'),
	url(r'^imageUpload/', views.FileView.as_view()),
	]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plagiarismchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rest_framework import routers
from checker.views import ApiViewSet
from django.conf import settings
from django.views.static import serve
router = routers.DefaultRouter()
router.register(r'/api',ApiViewSet)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('checker.urls')),
    url(r'^doc',include(router.urls))
]

if settings.DEBUG:
    urlpatterns+=[
        url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,})
    ]

templates/dash.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        {% block title %}{% endblock %}
        <title>Dashboard  </title>
        <!-- Bootstrap core CSS-->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'dashboard/bootstrap/css/bootstrap.min.css' %}" />
        <!-- Custom fonts for this template-->
        <link rel="stylesheet" type="text/css" href="{% static 'dashboard/font-awesome/css/font-awesome.min.css' %}" />
        <!-- Page level plugin CSS-->
        <link href="{% static 'dashboard/vendor/datatables/dataTables.bootstrap4.css' %}" />
        <!-- Custom styles for this template-->
        <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/sb-admin.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/custom.css' %}" />
        {% block stylesheet %}{% endblock %}
    </head>

    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
        <!-- Navigation-->
        {% include "sidebar.html" %}
        <div class="content-wrapper">
            <!-- container-fluid-->
            {% block body %}{% endblock %}
            <!-- /.container-fluid-->
            <!-- /.content-wrapper-->
            <footer class="sticky-footer">
                <div class="container">
                    <div class="text-center">
                        <small>Copyright © ChronicleScan 2019</small>
                    </div>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            <a class="btn btn-primary" href="/logout">Logout</a>
                        </div>
                    </div>
                </div>
            </div>

            <!--Dynamic Javascript-->
            <script type="text/javascript" src="{% static 'dashboard/jquery/jquery.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'dashboard/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
            <!-- Core plugin JavaScript-->
            <script type="text/javascript" src="{% static 'dashboard/jquery-easing/jquery.easing.min.js' %}"></script>

            <!-- Page level plugin JavaScript-->

            {% block javascript %}{% endblock %}
        </div>
    </body>

</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Google Analytics script start -->
  <!-- <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-78952927-1', 'auto');
    ga('send', 'pageview');
  </script> -->
  <!-- Google Analytics script end -->
  <link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Chronicle Scan</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="/static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="/static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href='https://fonts.googleapis.com/css?family=Amaranth:700italic' rel='stylesheet' type='text/css'>

    <script>
               var myvar;
           function spin()

               {
                 document.getElementById("hi").style.display="none";
                 document.getElementById("loader").style.display="block";

                   myvar = setTimeout(showPage,30000)
               }
               function showPage()
               {
                   document.getElementById("loader").style.display="none";
                   document.getElementById("hi").style.display="block";
               }



           </script>






                   <style>


           #loader
                       {
                         display: none;
                         margin:auto;
                         margin-top: 250px;
                           height: 100px;
                           width: 100px;

                           background-color: blue;
                           border-radius: 100%;
                           -webkit-animation:spin 2s linear infinite;
                       }
                       @-webkit-keyframes spin
                       {
                           0%
                           {
                             background-radius:90%;
                               background-color: aqua;
                           }
                           25%
                           {
                            border-radius: 70%;

                               background-color: red;
                           }
                           50%
                           {
                             border-radius: 40%;
                               background-color: darkblue;
                           }
                           75%
                           {  border-radius: 10%;
                               background-color: darkorange;
                           }

                           100%
                           {
                               background-color: dimgray;
                           }
                       }



                       #hi
                       {
                         display: block;
                       }

                       #b{
                        display:inline-block;
                       }
                       a{
                        color:white;
                       }
                   </style>

</head>

<body>
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="/" class="brand-logo" style="font-family: 'Amaranth', sans-serif;font-size:300%;color:green;"><i class="material-icons" style="float:left;">code</i>&nbspChronicleScan</a>
      <ul class="right hide-on-med-and-down">
        <!-- <li><a  style="color:black;" href="/">Home</a></li> -->
        <!-- <li><a href="/test/">Languages</a></li> -->
          <!-- <ul id='dropdown1' class='dropdown-content'>
            <li><a href="#!">C</a></li>
            <li><a href="#!">Java</a></li>
            <li class="divider"></li>
            <li><a href="#!">Php</a></li>
          </ul> -->
          <!-- <li><a href="/forums">Forum</a></li> -->
        <!-- <li><a style="color:black;" href="/contact">Contact Us</a></li> -->
        {% if user.is_authenticated %}
       <!--  <li><a class="dropdown-button" style="color:black;" data-beloworigin="true" data-activates="dropdown1">Welcome {{user.username}} ▼</a></li> -->
          <!-- <ul id='dropdown1' class='dropdown-content'> -->
            <ul>

            
            <li><a style="color:black;" href="/dashboard">Dashboard</a></li>
            <!-- <li><a style="color:black;" href="/dashboard">Settings</a></li> -->
            <li><a style="color:black;" href="/logout">Logout</a></li>
          </ul>
        {% else %}
       <!--  <li><a class="dropdown-button" style="color:black;" data-beloworigin="true" data-activates="dropdown1">Welcome Guest ▼</a></li> -->
        <!-- <ul  id='dropdown1' class='dropdown-content'> -->
          <ul>



          <li><a style="color:black;" href="/login">Login</a></li>
          <li><a style="color:black;" href="/register">Register</a></li>

        </ul>

        {% endif %}
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a style="color:black;" href="/">Home</a></li>
        <!-- <li><a href="/test/">Languages</a></li>
        <li><a href="/forums">Forum</a></li> -->
        <li><a style="color:black;" href="/contact">Contact Us</a></li>
        {% if user.is_authenticated %}
        <li><a style="color:black;" class="dropdown-button" data-beloworigin="true" data-activates="dropdown2">Welcome {{user.username}} ▼</a></li>
          <ul id='dropdown2' class='dropdown-content'>

            <li><a style="color:black;" href="/logout">Logout</a></li>
          </ul>
        {% else %}
        <li><a style="color:black;" href="/login">Register/Login</a></li>
        {% endif %}

      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

 {% block body %}
  {% endblock %}

<!-- 
<footer class="page-footer white">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="black-text">Company Bio</h5>
          <p class="black-text text-lighten-4">We are a team of college students working on this project like it's our full time job.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="black-text">Connect</h5>
          <ul>
            <li><a class="black-text" href="/">Home</a></li>
            <li><a class="black-text" href="/contact">Contact Us</a></li>

          </ul>
        </div>
      </div>
    </div>

  </footer> -->


  <!--  Scripts-->
  <script src="static/js/jquery.min.js"></script>
  <script src="static/js/materialize.js"></script>
  <script src="static/js/init.js"></script>
  <!--Start of Tawk.to Script-->

  <!--End of Tawk.to Script-->

  </body>
</html>

templates/footer1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Chronicle Scan</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- styles -->
  <link href="/static/selacao/css/bootstrap.css" rel="stylesheet">
  <link href="/static/selacao/css/bootstrap-responsive.css" rel="stylesheet">
  <link href="/static/selacao/css/prettyPhoto.css" rel="stylesheet">
  <link href="/static/selacao/font/stylesheet.css" rel="stylesheet">
  <link href="/static/selacao/css/animate.css" rel="stylesheet">
  <link href="/static/selacao/css/flexslider.css" rel="stylesheet">
  <link rel="stylesheet" media="screen" href="/static/selacao/css/sequencejs.css">
  <link href="/static/selacao/css/style.css" rel="stylesheet">
  <link href="/static/selacao/color/default.css" rel="stylesheet">

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/selacao/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/selacao/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/selacao/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="/static/selacao/ico/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="/static/selacao/ico/favicon.ico">
  {% load staticfiles %}

</head>

<body>
  <header>

    <!-- start top -->
    <div id="topnav" class="navbar navbar-fixed-top default">
      <div class="navbar-inner">
        <div class="container">
          <div class="logo">
            <!-- <img src="/static/selacao/img/logo.png" alt=""> -->
            <a class="brand" href="index.html"></a>
          </div>
          <div class="navigation">
            <nav>
              <ul class="nav pull-right">
                 {% if user.is_authenticated %}
                <li class="current"><a href="#featured">Home</a></li>
                <li><a href="/dashboard">Dashboard</a></li>
                <li><a href="/logout">Logout</a></li>
                <!-- <li><a href="#works">Works</a></li> -->
                <!-- <li><a href="#contact">Contact</a></li> -->
                <!-- <li class="dropdown">
                  <a href="#">More</a>
                  <ul class="dropdown-menu"> -->
                    <!-- <li><a href="components.html" class="external">Components</a></li>
                    <li><a href="icons.html" class="external">Icons</a></li>
                  </ul> -->
                 {% else %}
                 <li class="current"><a href="#featured">Home</a></li>
                 <li><a href="/login">Login</a></li>
                <li><a href="/register">Register</a></li>
                 {% endif %}
              </ul>
            </nav>
          </div>
          <!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <!-- end top -->
  </header>
 
 {% block body %}
  {% endblock %}

<!-- 
<footer class="page-footer white">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="black-text">Company Bio</h5>
          <p class="black-text text-lighten-4">We are a team of college students working on this project like it's our full time job.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="black-text">Connect</h5>
          <ul>
            <li><a class="black-text" href="/">Home</a></li>
            <li><a class="black-text" href="/contact">Contact Us</a></li>

          </ul>
        </div>
      </div>
    </div>

  </footer> -->


  <!-- Javascript Library Files -->
  <script src="/static/selacao/js/jquery.min.js"></script>
  <script src="/static/selacao/js/jquery.easing.js"></script>
  <script src="/static/selacao/js/bootstrap.js"></script>
  <script src="/static/selacao/js/jquery.lettering.js"></script>
  <script src="/static/selacao/js/parallax/jquery.parallax-1.1.3.js"></script>
  <script src="/static/selacao/js/nagging-menu.js"></script>
  <script src="/static/selacao/js/sequence.jquery-min.js"></script>
  <script src="/static/selacao/js/sequencejs-options.sliding-horizontal-parallax.js"></script>
  <script src="/static/selacao/js/portfolio/jquery.quicksand.js"></script>
  <script src="/static/selacao/js/portfolio/setting.js"></script>
  <script src="/static/selacao/js/jquery.scrollTo.js"></script>
  <script src="/static/selacao/js/jquery.nav.js"></script>
  <script src="/static/selacao/js/modernizr.custom.js"></script>
  <script src="/static/selacao/js/prettyPhoto/jquery.prettyPhoto.js"></script>
  <script src="/static/selacao/js/prettyPhoto/setting.js"></script>
  <script src="/static/selacao/js/jquery.flexslider.js"></script>

  <!-- Contact Form JavaScript File -->
  <script src="/static/selacao/contactform/contactform.js"></script>

  <!-- Template Custom Javascript File -->
  <script src="/static/selacao/js/custom.js"></script>


  <!--End of Tawk.to Script-->

  </body>
</html>

templates/sidebar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/">ChronicleScan</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href=".">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Dashboard</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
                <a class="nav-link" href="{% url 'checker:model_form_upload' %}">
                    <i class="fa fa-fw fa-database"></i>
                    <span class="nav-link-text">File Upload</span>
                </a>
            </li>
            <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
                <a class="nav-link" href="#">
                    <i class="fa fa-fw fa-table"></i>
                    <span class="nav-link-text">DeepCheck</span>
                </a>
            </li> -->
            <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ajax">
                <a class="nav-link" href=".">
                    <i class="fa fa-fw fa-angellist"></i>
                    <span class="nav-link-text">User Settings</span>
                </a>
            </li> -->
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                {% if request.user.institution.flag  == 1 %}
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-user"></i>
                    <span class="nav-link-text">Users</span>
                </a>
                
                <ul class="sidenav-second-level collapse" id="collapseComponents">
                    <li>
                        <a href="{% url 'checker:addusers' %}">Add User</a>
                    </li>
                    <li>
                        <a href="{% url 'checker:subusers' %}">User List</a>
                    </li>
                </ul>
                {% endif %}
            </li>
            <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-file"></i>
                    <span class="nav-link-text">Example Pages</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseExamplePages">
                    <li>
                        <a href="#">Login Page</a>
                    </li>
                    <li>
                        <a href="#">Registration Page</a>
                    </li>
                    <li>
                        <a href="#">Forgot Password Page</a>
                    </li>
                    <li>
                        <a href="#">Blank Page</a>
                    </li>
                </ul>
            </li> -->
            <!-- <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-sitemap"></i>
                    <span class="nav-link-text">Menu Levels</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseMulti">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
                        <ul class="sidenav-third-level collapse" id="collapseMulti2">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="#">
                    <i class="fa fa-fw fa-link"></i>
                    <span class="nav-link-text">Link</span>
                </a>
            </li> -->
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-envelope"></i>
                    <span class="d-lg-none">Messages
                        <span class="badge badge-pill badge-primary">12 New</span>
                    </span>
                    <span class="indicator text-primary d-none d-lg-block">
                        <i class="fa fa-fw fa-circle"></i>
                    </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">New Messages:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>David Miller</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>Jane Smith</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <strong>John Doe</strong>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all messages</a>
                </div>
            </li> -->
            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-bell"></i>
                    <span class="d-lg-none">Alerts
                        <span class="badge badge-pill badge-warning">6 New</span>
                    </span>
                    <span class="indicator text-warning d-none d-lg-block">
                        <i class="fa fa-fw fa-circle"></i>
                    </span>
                </a>
                <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                    <h6 class="dropdown-header">New Alerts:</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <span class="text-success">
                            <strong>
                                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
                        </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <span class="text-danger">
                            <strong>
                                <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
                        </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <span class="text-success">
                            <strong>
                                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
                        </span>
                        <span class="small float-right text-muted">11:21 AM</span>
                        <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item small" href="#">View all alerts</a>
                </div>
            </li>
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0 mr-lg-2">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for...">
                        <span class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </div>
</nav>